# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bookinfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x62ookinfo.proto\x12\x08\x62ookinfo\"\x87\x01\n\x08\x42ookItem\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t\x12\x11\n\tpublisher\x18\x04 \x01(\t\x12\x0c\n\x04isbn\x18\x05 \x01(\t\x12\r\n\x05price\x18\x06 \x01(\r\x12 \n\x04type\x18\x07 \x01(\x0e\x32\x12.bookinfo.BookType\"\x1d\n\rSearchRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"G\n\x0eSearchResponse\x12\x13\n\x0bstatus_code\x18\x01 \x01(\x05\x12 \n\x04item\x18\x02 \x01(\x0b\x32\x12.bookinfo.BookItem*D\n\x08\x42ookType\x12\x08\n\x04\x42OOK\x10\x00\x12\r\n\tPAPERBACK\x10\x01\x12\n\n\x06POCKET\x10\x02\x12\x08\n\x04MOOK\x10\x03\x12\t\n\x05OTHER\x10\x63\x32N\n\rMultiBookInfo\x12=\n\x06Search\x12\x17.bookinfo.SearchRequest\x1a\x18.bookinfo.SearchResponse0\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bookinfo_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BOOKTYPE._serialized_start=270
  _BOOKTYPE._serialized_end=338
  _BOOKITEM._serialized_start=29
  _BOOKITEM._serialized_end=164
  _SEARCHREQUEST._serialized_start=166
  _SEARCHREQUEST._serialized_end=195
  _SEARCHRESPONSE._serialized_start=197
  _SEARCHRESPONSE._serialized_end=268
  _MULTIBOOKINFO._serialized_start=340
  _MULTIBOOKINFO._serialized_end=418
# @@protoc_insertion_point(module_scope)
